const jwt = require('jsonwebtoken'); 
require('dotenv').config()

function authenticateToken(req,res,next){
    const token = req.header('x-auth-token'); 

    if (token === null) return res.sendStatus(401); 

    //Verify the access token by comparing it to another generated by the same secret
    jwt.verify(token, process.env.ACCESS_TOKEN_SECRET, (err, user)=> {
        if(err) return res.sendStatus(403)
        req.user = user //allow user (grabbed from the authentication) to be accessible through req.user 
        next(); 
    })

}

module.exports = {authenticateToken}; 